version: '3.8'

services:
  db:
    image: timescale/timescaledb:latest-pg17
    environment:
      POSTGRES_USER: news
      POSTGRES_PASSWORD: newspass
      POSTGRES_DB: news
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U news"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - METRICS_DATABASE_URL=postgres://news:newspass@db:5432/news?sslmode=disable
      - HOST=0.0.0.0
      - PORT=8080
      - CACHE_TTL_SECONDS=60
      - ENABLE_HSTS=false
    volumes:
      - .:/app
      - /app/tmp
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
